image: cloudrexx/web:PHP7.0

clone:
  depth: 1 # only clone the last commit

pipelines:
  default:
    - step:
        script:
          - ls
        services:
          - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: "\0"
        MYSQL_DATABASE: 'dev'
