clone:
  depth: 1 # only clone the last commit
pipelines:
  default:
    - step:
        image: php:7.0-apache
        script:
          - ls
        services:
          - maria
definitions:
  services:
    maria:
      image: mariadb
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: 'dev'