clone:
  depth: 1
pipelines:
  default:
    - step:
        image: cloudrexx/web:PHP7.0
        script:
          - ls
        services:
          - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: 'cloudrexx'
        MYSQL_DATABASE: 'dev'