clone:
  depth: 1
pipelines:
  default:
    - step:
        image: php:7.0-apache
        script:
          - ls
        services:
          - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: "\0"
        MYSQL_DATABASE: 'dev'