clone:
  depth: 1
pipelines:
  default:
    - step:
        image: php:7.0-apache
        script:
          - ls
        services:
          - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: "123456"
        MYSQL_DATABASE: 'dev'