image: cloudrexx/web:PHP7.0

clone:
  depth: 1 # only clone the last commit

pipelines:
  default:
    - step:
        script:
          - mysql -uroot < echo "SET @@SQL_MODE = CONCAT(@@SQL_MODE, ',NO_ENGINE_SUBSTITUTION');"
          - mysql -uroot < ./installer/dump/contrexx_dump_structure.sql
          - mysql -uroot < ./installer/dump/contrexx_dump_structure.sql
          - ./cx wb test 2>&1
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: 'dev'
